#!/bin/bash

set -e
set -o pipefail

kernel_version=$1
destination=$2

script_dir=$(dirname "${BASH_SOURCE[0]}")
source "${script_dir}/deps/utils.sh"

for package_config in "$PACKAGES_DIR"/*.yml; do
    echo_color "Checking for kmod packages in $package_config"

    mapfile -t repos < <(yq -o=json -I=0 '.[]' "$package_config")

    for repo_packages in "${repos[@]}"; do
        # repo_packages is a single JSON snippet
        repo=$(yq '.repo' <<<"$repo_packages")
        repo_file=$(yq '.repo_file' <<<"$repo_packages")
        disable_repo=$(yq '.disable_repo' <<<"$repo_packages")
        mapfile -t kmod_packages < <(yq -r '.kmods[].package' <<<"$repo_packages")
        mapfile -t kmod_names < <(yq -r '.kmods[].akmod' <<<"$repo_packages")

        if [ -n "${kmod_packages[*]}" ]; then
            echo_color "Installing kmod packages for $package_config: '$repo'"

            if [ "$repo" = "fedora" ]; then
                dnf -y install "${kmod_packages[@]}"

            elif [ ! -f "${REPOS_DIR}/${repo_file}" ]; then
                enable_repo "$repo_file" "$repo"
                dnf -y install "${kmod_packages[@]}"
                [ "$disable_repo" = "false" ] || disable_repo "$repo_file" "$repo"

            else
                enable_repo_extern "$repo_file" "$repo"
                dnf -y install "${kmod_packages[@]}"
                [ "$disable_repo" = "false" ] || disable_repo_extern "$repo_file" "$repo"
            fi
        fi

        for name in "${kmod_names[@]}"; do
            echo_color "Building kmod package $package_config: '$name'"

            akmods --force --kernel "$kernel_version" --kmod "$name"

            if ! test -n "$(find "/var/cache/akmods/" -name '*.rpm' -print -quit)"; then
                echo_error "Failed to build kmod $name"
                for log in /var/cache/akmods/*/*.failed.log; do
                    cat "$log"
                done
                exit 1
            fi

            mkdir -p "${destination}/${name}"
            mv /var/cache/akmods/*/*.rpm "${destination}/${name}/"
            ls "${destination}/${name}/"

            echo_success "Successfully built kmod for $package_config: '$name'"
        done
    done

done
