#!/bin/bash

set -e
set -o pipefail

kernel_version=$1
destination=$2

source "${SCRIPTS_DIR}/utils.sh"

for package_config in "$PACKAGES_DIR"/*.yml; do
    echo_color "Checking for kmod packages for $package_config"

    readarray repos < <(yq -o=j -I=0 '.[]' "$package_config")
    for repo_packages in "${repos[@]}"; do
        # repo is a single json snippet
        repo=$(echo "$repo_packages" | yq '.repo' -)
        repo_file=$(echo "$repo_packages" | yq '.repo_file' -)
        readarray -t packages_kmods < <(echo "$repo_packages" | yq '.kmods[]' | envsubst)

        if [ -n "${packages_kmods[*]}" ]; then
            echo_color "Installing kmod packages for $package_config: '$repo'"

            if [ "$repo" = "fedora" ]; then
                dnf -y install "${packages_kmods[@]}"

            elif [ ! -f "${REPOS_DIR}/${repo_file}" ]; then
                enable_repo "$repo_file" "$repo"
                dnf -y install "${packages_kmods[@]}"
                disable_repo "$repo_file" "$repo"

            else
                enable_repo_extern "$repo_file" "$repo"
                dnf -y install "${packages_kmods[@]}"
                disable_repo_extern "$repo_file" "$repo"
            fi
        fi

        for name in "${packages_kmods[@]}"; do
            echo_color "Building kmod package for '$name'"

            akmods --force --kernel "$kernel_version" --kmod "$name"

            if ! test -n "$(find "/var/cache/akmods/" -name '*.rpm' -print -quit)"; then
                echo_error "Failed to build kmod $name"
                for log in /var/cache/akmods/*/*.failed.log; do
                    cat "$log"
                done
                exit 1
            fi

            mkdir -p "${destination}/${name}"
            mv /var/cache/akmods/*/*.rpm "${destination}/${name}/"
            ls "${destination}/${name}/"
        done
    done

done
