#!/bin/bash

set -e
set -o pipefail

yml_file=$1
package_config="${PACKAGES_DIR}/${yml_file}"

source "$(dirname "${BASH_SOURCE[0]}")/deps/repo.sh"
source "$(dirname "${BASH_SOURCE[0]}")/deps/gnome-extensions.sh"
source "$(dirname "${BASH_SOURCE[0]}")/deps/dconf.sh"

if [ ! -f "$package_config" ]; then
	echo_error "Config file not found: $package_config"
	exit 1
fi

echo_color "\n==== Installing $yml_file ===="

mapfile -t repos < <(yq -o=j -I=0 '.[]' "$package_config")
for repo_packages in "${repos[@]}"; do
	# repo is a single json snippet
	repo=$(yq '.repo' <<<"$repo_packages")
	repo_file=$(yq '.repo_file' <<<"$repo_packages")
	disable_repo=$(yq '.disable_repo' <<<"$repo_packages")
	pre_install_command=$(yq '.pre_install_command' <<<"$repo_packages")
	post_install_command=$(yq '.post_install_command' <<<"$repo_packages")
	mapfile -t packages_install < <(yq '.install[]' <<<"$repo_packages" | envsubst)
	mapfile -t packages_remove < <(yq '.remove[]' <<<"$repo_packages" | envsubst)
	mapfile -t packages_extensions < <(yq '.extensions[]' <<<"$repo_packages" | envsubst)
	mapfile -t kmod_names < <(yq -r '.kmods[].akmod' <<<"$repo_packages")
	mapfile -t dconf_configs < <(yq '.dconf[]' <<<"$repo_packages")

	# Kmods
	if [ -n "${kmod_names[*]}" ]; then
		echo_color "Installing kmods for $yml_file: '$repo'"

		for name in "${kmod_names[@]}"; do
			for rpm_package in "${KMODS_RPM_DIR}"/"${name}"/*.rpm; do
				kmod_packages_paths+=("$rpm_package")
			done
		done

		if [ -z "${kmod_packages_paths[*]}" ]; then
			echo_error "Failed to get kmod packages in ${KMODS_RPM_DIR}/${name}/"
			exit 1
		fi

		if [ "$repo" = "fedora" ]; then
			rpm-ostree install "${kmod_packages_paths[@]}"

		elif [ ! -f "${REPOS_DIR}/${repo_file}" ]; then
			enable_repo "$repo_file" "$repo"
			rpm-ostree install "${kmod_packages_paths[@]}"
			[ "$disable_repo" = "false" ] || disable_repo "$repo_file" "$repo"

		else
			enable_repo_extern "$repo_file" "$repo"
			rpm-ostree install "${kmod_packages_paths[@]}"
			[ "$disable_repo" = "false" ] || disable_repo_extern "$repo_file" "$repo"
		fi

	fi

	# Extensions
	if [ -n "${packages_extensions[*]}" ]; then
		echo_color "Installing extensions for $yml_file: '$repo'"

		for extension in "${packages_extensions[@]}"; do
			packages_install+=("$(yq '.package' <<<"$extension")")
			mapfile -t extension_dconfs < <(yq -r '.dconf[]' <<<"$extension")

			for extension_dconf in "${extension_dconfs[@]}"; do
				dconf_configs+=("$extension_dconf")
			done
		done
	fi

	## Packages
	if [ -z "${packages_install[*]}" ] &&
		[ -z "${packages_remove[*]}" ] &&
		[ -z "${kmod_names[*]}" ] &&
		[ -z "${dconf[*]}" ]; then
		echo_error "No packages / config defined for $yml_file: '$repo'"
		exit 1
	fi

	# Pre install
	if [ ! "$pre_install_command" = "null" ]; then
		echo_color "Running pre install command for $yml_file: '$repo'"
		echo "$pre_install_command"
		eval "$pre_install_command"
	fi

	# Packages - replace
	if [ -n "${packages_remove[*]}" ] && [ -n "${packages_install[*]}" ]; then
		if [ -n "${packages_install[*]}" ]; then
			echo_color "Replacing packages for $yml_file: '$repo'"

			if [ "$repo" = "fedora" ]; then
				rpm-ostree override remove "${packages_remove[@]}" --install "${packages_install[@]}"

			elif [ ! -f "${REPOS_DIR}/${repo_file}" ]; then
				enable_repo "$repo_file" "$repo"
				rpm-ostree override remove "${packages_remove[@]}" --install "${packages_install[@]}"
				[ "$disable_repo" = "false" ] || disable_repo "$repo_file" "$repo"

			else
				enable_repo_extern "$repo_file" "$repo"
				rpm-ostree override remove "${packages_remove[@]}" --install "${packages_install[@]}"
				[ "$disable_repo" = "false" ] || disable_repo_extern "$repo_file" "$repo"
			fi
		fi
	else
		# Packages - remove
		if [ -n "${packages_remove[*]}" ]; then
			echo_color "Removing packages for $yml_file: '$repo'"
			rpm-ostree override remove "${packages_remove[@]}"
		fi

		# Packages - install
		if [ -n "${packages_install[*]}" ]; then
			echo_color "Installing packages for $yml_file: '$repo'"

			if [ "$repo" = "fedora" ]; then
				rpm-ostree install "${packages_install[@]}"

			elif [ ! -f "${REPOS_DIR}/${repo_file}" ]; then
				enable_repo "$repo_file" "$repo"
				rpm-ostree install "${packages_install[@]}"
				[ "$disable_repo" = "false" ] || disable_repo "$repo_file" "$repo"

			else
				enable_repo_extern "$repo_file" "$repo"
				rpm-ostree install "${packages_install[@]}"
				[ "$disable_repo" = "false" ] || disable_repo_extern "$repo_file" "$repo"
			fi
		fi
	fi

	# Extension config
	if [ -n "${packages_extensions[*]}" ]; then
		enable_gnome_extensions packages_extensions
	fi

	# Dconf
	if [ -n "${dconf_configs[*]}" ]; then
		set_dconf dconf_configs
		dconf update
	fi

	# Post install
	if [ ! "$post_install_command" = "null" ]; then
		echo_color "Running post install command for $yml_file: '$repo'"
		echo "$post_install_command"
		eval "$post_install_command"
	fi

done

echo_color "Commiting changes to container"
ostree container commit

echo_success "Successfully built: $yml_file"
